### ISSUE TITLE
Blog content css is not properly implimented

### ISSUE THREAD

**Issue by Dave-lab12** [Xcceleran-do/Mindplex-landing-page#5]
# Description 
The sveltekit site blog content is not similar with the deployed version

some of the missing css I found 
```css
 .blog-heading[data-astro-cid-lrlibhk2] {
    color: var(--gray-6, #f2f2f2);
    font-family: Montserrat;
    font-size: 39px;
    font-style: normal;
    font-weight: 700;
    line-height: normal
 }

```
this is not converted to tailwind

## Deployed version
![image](https://github.com/Xcceleran-do/Mindplex-landing-page/assets/56738450/6601dd72-7ab5-45ac-8570-382f5d0e1805)

## Local version
![image](https://github.com/Xcceleran-do/Mindplex-landing-page/assets/56738450/4a6d3c3b-5ed8-4ec7-ac74-1edb44e9bc29)
